package app.src.main.java.botmaker;
/*
 * This source file was generated by the Gradle 'init' task
 */

import app.src.main.java.gui.Gui; // Jag jar definitivt gjort något fel för att ha så långa imports men skit samma. We ball.
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Gui gui = new Gui();
        System.out.println(new App().getGreeting());
    }
}
