package botmaker;
/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.ArrayList;
import java.util.List;

import gui.Gui; // Jag jar definitivt gjort något fel för att ha så långa imports men skit samma. We ball.
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        List<String> actions = new ArrayList();
        actions.add("Press");
        actions.add("down");
        actions.add("up");
        Gui gui = new Gui(actions);
        System.out.println(new App().getGreeting());
    }
}
